name: 01 - Building Blocks
on: # EVENTS that trigger the workflow
  push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: |
          echo "I Will Succeed"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye, World!"
