name: 05 - 1 - Event Filters and Activity Types
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Single step job
        run: echo "Running whenever a PR is opened or synchronyzed AND base branch is main"

