name: 08 - Using variables
on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: workflow env variable
  OVERWRITTEN: I will be overwritten

jobs:
  scho:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: job env variable
      OVERWRITTEN: I have been overwritten at the job level
    steps:
      - name: Print env vars
        env:
          STEP_VAR: step env variable
          step_var2: Another step var
        run: |
          echo "step env vat: $STEP_VAR"
          echo "step env var 2: $step_var2"
          echo "Job env var: $JOB_VAR"
          echo "workflow env var: $WORKFLOW_VAR"
          echo "Overwritten: $OVERWRITTEN"
      - name: overwrite job variable
        env:
          OVERWRITTEN: I have been overwritten at the step level
        run: "echo step env var: Overwritten: $OVERWRITTEN"
